#!/bin/bash

# Google Vertex AI MCP Server - Multimedia AI Tools Setup Script
# This script helps you set up your Google Cloud environment for image/video generation

set -e

echo "🎨 Google Vertex AI MCP Server - Multimedia AI Tools Setup"
echo "=========================================================="
echo ""

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    echo "❌ Google Cloud CLI (gcloud) is not installed."
    echo "Please install it from: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Check if user is authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q .; then
    echo "🔐 Please authenticate with Google Cloud first:"
    echo "gcloud auth login"
    exit 1
fi

echo "✅ Google Cloud CLI is installed and authenticated"
echo ""

# Get current project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || echo "")

if [ -z "$CURRENT_PROJECT" ]; then
    echo "❌ No Google Cloud project is set."
    echo "Please set a project: gcloud config set project YOUR_PROJECT_ID"
    exit 1
fi

echo "📁 Current project: $CURRENT_PROJECT"
echo ""

# Ask user if they want to use current project or create new one
read -p "Do you want to use the current project '$CURRENT_PROJECT'? (y/n): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    read -p "Enter your Google Cloud Project ID: " PROJECT_ID
    gcloud config set project "$PROJECT_ID"
    CURRENT_PROJECT="$PROJECT_ID"
    echo "✅ Project set to: $CURRENT_PROJECT"
    echo ""
fi

# Enable required APIs
echo "🔧 Enabling required APIs..."
gcloud services enable aiplatform.googleapis.com
gcloud services enable vision.googleapis.com
gcloud services enable videointelligence.googleapis.com
echo "✅ APIs enabled successfully"
echo ""

# Check if billing is enabled
BILLING_ACCOUNT=$(gcloud billing projects describe "$CURRENT_PROJECT" --format="value(billingAccountName)" 2>/dev/null || echo "")

if [ -z "$BILLING_ACCOUNT" ]; then
    echo "⚠️  Billing is not enabled for this project."
    echo "Please enable billing at: https://console.cloud.google.com/billing/projects/$CURRENT_PROJECT"
    echo "Billing is required for Vertex AI services to work."
    echo ""
else
    echo "✅ Billing is enabled: $BILLING_ACCOUNT"
    echo ""
fi

# Create service account
echo "👤 Creating service account for Vertex AI..."
SERVICE_ACCOUNT_NAME="vertex-ai-user"
SERVICE_ACCOUNT_EMAIL="$SERVICE_ACCOUNT_NAME@$CURRENT_PROJECT.iam.gserviceaccount.com"

# Check if service account already exists
if gcloud iam service-accounts describe "$SERVICE_ACCOUNT_EMAIL" &>/dev/null; then
    echo "✅ Service account already exists: $SERVICE_ACCOUNT_EMAIL"
else
    gcloud iam service-accounts create "$SERVICE_ACCOUNT_NAME" \
        --display-name="Vertex AI User" \
        --description="Service account for Vertex AI MCP Server"
    echo "✅ Service account created: $SERVICE_ACCOUNT_EMAIL"
fi

# Assign IAM roles
echo "🔑 Assigning IAM roles..."
gcloud projects add-iam-policy-binding "$CURRENT_PROJECT" \
    --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
    --role="roles/aiplatform.user"

gcloud projects add-iam-policy-binding "$CURRENT_PROJECT" \
    --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
    --role="roles/aiplatform.developer"

gcloud projects add-iam-policy-binding "$CURRENT_PROJECT" \
    --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
    --role="roles/storage.objectViewer"

echo "✅ IAM roles assigned successfully"
echo ""

# Create and download service account key
echo "🔐 Creating service account key..."
KEY_FILE="vertex-ai-key.json"
gcloud iam service-accounts keys create "$KEY_FILE" \
    --iam-account="$SERVICE_ACCOUNT_EMAIL"

echo "✅ Service account key downloaded to: $KEY_FILE"
echo ""

# Create .env file
echo "📝 Creating .env configuration file..."
cat > .env << EOF
# Google Vertex AI MCP Server Configuration
# Generated by setup script on $(date)

# AI Provider
AI_PROVIDER=vertex

# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT=$CURRENT_PROJECT
GOOGLE_CLOUD_LOCATION=us-central1
GOOGLE_APPLICATION_CREDENTIALS=./$KEY_FILE

# AI Model Configuration
VERTEX_MODEL_ID=gemini-2.0-flash-exp

# Generation Parameters
AI_TEMPERATURE=0.7
AI_MAX_OUTPUT_TOKENS=8192
AI_USE_STREAMING=true

# Retry Configuration
AI_MAX_RETRIES=3
AI_RETRY_DELAY_MS=1000
EOF

echo "✅ .env file created successfully"
echo ""

# Set file permissions
chmod 600 "$KEY_FILE"
chmod 600 .env

echo "🔒 File permissions set (600) for security"
echo ""

# Test configuration
echo "🧪 Testing configuration..."
if [ -f ".env" ] && [ -f "$KEY_FILE" ]; then
    echo "✅ Configuration files created successfully"
    echo "✅ Service account key downloaded"
    echo "✅ IAM roles assigned"
    echo "✅ APIs enabled"
    echo ""
    echo "🎉 Setup complete! You can now use the multimedia AI tools."
    echo ""
    echo "📋 Next steps:"
    echo "1. Start the MCP server: npm start"
    echo "2. Test with: check_api_setup tool"
    echo "3. Generate your first image with: generate_image tool"
    echo ""
    echo "⚠️  Important: Keep your service account key secure and never commit it to version control!"
    echo "   The key file ($KEY_FILE) is already added to .gitignore"
else
    echo "❌ Setup failed. Please check the error messages above."
    exit 1
fi

echo ""
echo "📚 For more information, see README_MULTIMEDIA.md"
echo "🔗 Google Cloud Console: https://console.cloud.google.com/vertex-ai?project=$CURRENT_PROJECT"

