/**
 * thumbnail-store.ts — a picture the editor captured must survive being stored.
 *
 * ─── why this exists (2026-08-22) ───────────────────────────────────────────
 * Project cover art vanished from the home screen. Nothing threw and nothing logged: the capture
 * ran every 20s, produced a correct image, handed it to ProjectModel — and then
 * `LocalProjectsModel.cappedThumb` measured it against a 96KB limit and stored '' instead.
 *
 * Both halves were right on their own. 458aea9 raised the capture to a 1024px short side so the
 * AI's vision pass could read UI detail. 63e8286 added the 96KB cap because data URIs in
 * `recently_opened_project.json` had grown that file to 103MB, and every thumbnail change
 * re-serialised the whole of it synchronously. Together they guaranteed an empty thumbnail: a
 * 1024-short-side PNG of a game screen is 200KB-2MB. 13 of the 14 most recently opened projects
 * held a zero-length thumbURI.
 *
 * The root problem is not the cap's value. It is that images were being kept in a settings file
 * at all, so the only lever available was "how much of the picture are we willing to delete".
 * Thumbnails belong on disk. The entry keeps a path, the settings file goes back to being small,
 * the sync rewrite stops being a freeze, and no size guard has to choose between a huge file and
 * no cover art.
 *
 * The inline path survives for WEB_MODE, which has no userData directory. It is now a fallback
 * carrying a ~30KB tile rather than the main road carrying a megabyte.
 *
 * Deliberately free of electron, node and DOM imports: LocalProjectsModel cannot be loaded in a
 * test (it pulls in electron-store, GitStore and the platform layer), so the decisions that lost
 * the cover art live here, where they can be run directly.
 */

export interface ParsedDataUri {
    mime: string;
    base64: string;
}

/**
 * Split a data URI into its mime type and payload.
 *
 * Returns null for anything that is not a base64 data URI — a remote URL, a file path, an empty
 * string. Callers treat null as "nothing to store", never as an error worth failing a save over.
 */
export function parseDataUri(uri: string | undefined | null): ParsedDataUri | null {
    if (!uri || typeof uri !== 'string') return null;

    const match = /^data:([^;,]+);base64,(.+)$/s.exec(uri.trim());
    if (!match) return null;

    const [, mime, base64] = match;
    if (!mime || !base64) return null;

    return { mime, base64 };
}

/** File extension for the tile, so the file is what its name claims. */
function extensionFor(mime: string): string {
    if (/jpe?g/i.test(mime)) return 'jpg';
    if (/webp/i.test(mime)) return 'webp';
    return 'png';
}

/**
 * A project id reduced to something that can only name a file inside the thumbs directory.
 *
 * Ids are generated by `guid()` and are already safe, but they arrive here from a settings file
 * a user can edit, and this value is concatenated into a path.
 */
function safeId(id: string): string {
    // Dots are stripped along with everything else. The extension is appended separately, so an
    // id never needs one — and allowing them leaves `..` reachable in the middle of a name.
    const cleaned = String(id || '').replace(/[^a-zA-Z0-9_-]/g, '_');
    return cleaned || 'untitled';
}

export type ThumbnailWritePlan =
    | { kind: 'file' }
    | { kind: 'inline'; uri: string }
    | { kind: 'drop'; reason: string };

/**
 * Decide where a captured thumbnail goes.
 *
 * The rule the original code broke: "too big to inline" may only become "no cover art" when
 * there is genuinely nowhere else to put it.
 */
export function planThumbnailWrite(args: {
    dataUri: string | undefined;
    hasFileStore: boolean;
    maxInlineBytes: number;
}): ThumbnailWritePlan {
    const { dataUri, hasFileStore, maxInlineBytes } = args;

    if (!parseDataUri(dataUri)) {
        return { kind: 'drop', reason: 'the thumbnail is empty or is not a base64 data URI' };
    }

    if (hasFileStore) return { kind: 'file' };

    if (dataUri!.length <= maxInlineBytes) return { kind: 'inline', uri: dataUri! };

    return {
        kind: 'drop',
        reason:
            `the thumbnail is ${Math.round(dataUri!.length / 1024)}KB, over the ${Math.round(maxInlineBytes / 1024)}KB ` +
            `inline limit, and this platform has no thumbnail directory to write it to`,
    };
}

export interface ThumbnailFileIO {
    /** Directory thumbnails are written to. */
    dir: string;
    join(...parts: string[]): string;
    makeDirectory(path: string): Promise<void>;
    writeFile(path: string, blob: Buffer | string): Promise<void>;
}

/** Decode base64 without assuming node's Buffer or the browser's atob is the one present. */
function decodeBase64(base64: string): Buffer | Uint8Array {
    if (typeof Buffer !== 'undefined') return Buffer.from(base64, 'base64');

    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
}

/**
 * Write a thumbnail to the thumbs directory and return the path written.
 *
 * Returns null on any failure. A thumbnail is decoration: it must never take a project load or a
 * project list with it.
 */
export async function saveThumbnailFile(
    io: ThumbnailFileIO,
    id: string,
    dataUri: string,
): Promise<string | null> {
    const parsed = parseDataUri(dataUri);
    if (!parsed) return null;

    try {
        await io.makeDirectory(io.dir);

        const filePath = io.join(io.dir, `${safeId(id)}.${extensionFor(parsed.mime)}`);
        // The decoded bytes, not the base64 text. Storing the text would keep the 33% overhead
        // that helped produce the 103MB settings file in the first place.
        await io.writeFile(filePath, decodeBase64(parsed.base64) as Buffer);

        return filePath;
    } catch (e: any) {
        console.warn('[thumbnails] Could not write thumbnail to disk:', e?.message || e);
        return null;
    }
}

export interface ThumbnailBearingEntry {
    /** Path to the thumbnail on disk. Written since 2026-08-22. */
    thumbPath?: string;
    /** Inline data URI. Legacy entries, and the WEB_MODE fallback. */
    thumbURI?: string;
}

/**
 * A filesystem path as a `file://` URL the renderer will actually load.
 *
 * ─── why this is not `'file://' + path` (2026-08-31) ────────────────────────
 * It was, and on Windows that produced `file://C:%5CUsers%5C...%5C<id>.jpg` — wrong twice
 * over. `encodeURI` escapes a backslash to `%5C`, so every separator became part of one long
 * filename; and with two slashes a URL's authority runs to the next `/`, so `C:` was read as
 * the *host*. Chromium resolved nothing and every card on the home screen rendered empty,
 * while the capture went on writing perfectly good files into `userData/thumbs`.
 *
 * A POSIX path already starts with `/`, so the same concatenation happened to yield a valid
 * `file:///Users/...` there. That is the whole reason this survived review and shipped: the
 * bug is invisible on the platform it was written on.
 */
function toFileUrl(filePath: string): string {
    // Before encoding, or the separators encode as %5C rather than being separators.
    const slashed = filePath.replace(/\\/g, '/');

    // `//host/share/...` is a UNC path, and a UNC host is exactly what a file URL's authority
    // is for: `file://host/share/...`. Everything else — a drive path `C:/...` or a rooted
    // POSIX path — has an empty authority and needs the third slash of `file:///`.
    const body = slashed.startsWith('//') ? slashed.slice(2) : `/${slashed.replace(/^\/+/, '')}`;

    // encodeURI leaves `/` and `:` alone, which is what keeps the separators and the drive
    // letter readable. It also leaves characters that are legal in a path but would terminate
    // or break out of a css `url(...)` — both call sites build that string by concatenation —
    // so those are escaped by hand.
    return `file://${encodeURI(body).replace(/[()'"#?]/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase())}`;
}

/**
 * Where to point an <img> or a css `url()` for this project.
 *
 * Both consumers — projectsview's `background-image` string and ProjectCard's inline style — go
 * through here, so a new storage shape reaches the whole home screen at once. The previous shape
 * was read directly in two places, which is why nothing noticed one of them rendering nothing.
 *
 * Returns '' when there is nothing to show. Callers already treat '' as "no cover art".
 */
export function resolveThumbSrc(entry: ThumbnailBearingEntry | undefined | null): string {
    if (!entry) return '';

    if (entry.thumbPath) return toFileUrl(entry.thumbPath);

    return entry.thumbURI || '';
}
