name: Build xgenia-editor

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow from another workflow
  workflow_call:

  # release:
  #   types: [created]

jobs:
  build_xgenia_editor:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 16
            os: windows-latest
            platform: win32-x64
          # - node: 16
          #   os: macos-latest
          #   platform: darwin-arm64
          # - node: 16
          #   os: macos-latest
          #   platform: darwin-x64
          - node: 16
            os: ubuntu-latest
            platform: linux-x64

    steps:
      - if: ${{ matrix.platform == 'darwin-arm64' }}
        name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Init private submodule
        run: |
          git config --global url."https://x-access-token:${{ secrets.PRIVATE_SUBMODULE_PAT }}@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # - name: Clean up
      #   continue-on-error: true
      #   run: |
      #     npx rimraf node_modules
      #     npx lerna clean --yes

      - name: Install dependencies 🏗
        run: npm install

      - name: Build XGENIA Viewer (build bundles and copy them to XGENIA Editor)
        run: npm run build:editor:_viewer
        env:
          WORKSPACE_PATH: .

      - name: Build XGENIA Editor (build bundles etc and signing)
        run: npm run build:editor:_editor
        env:
          WORKSPACE_PATH: .
          TARGET_PLATFORM: ${{ matrix.platform }}
          DISABLE_SIGNING: true # disable for now

      - run: npm run build:editor:pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xgenia-editor-${{ matrix.platform }}-${{ github.head_ref }}-${{ github.sha }}
          path: publish
          retention-days: '12'
