name: GitHub Alert Workflow

on:
  push:
    branches:
      - main

jobs:
  alert:
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, '#')

    steps:
      - name: Send Webhook Alert
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.adaptive","contentUrl":null,"content":{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"🚨 **HIGH ALERT** 🚨\n[@${{ github.actor }}](https://github.com/${{ github.actor }}) just pushed directly to the main branch!\n\n⬆️ **Commit Details** ⬆️\nTitle: ${{ github.event.head_commit.message }}\nURL: ${{ github.event.compare }}","wrap":true}]}}]}' \
          "${{ secrets.ALERT_WEBHOOK_URL }}"
